export const AUTH_ACTIONS = {
  LOGIN_REQUEST: "AUTH_LOGIN_REQUEST",
  LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  LOGIN_FAILURE: "AUTH_LOGIN_FAILURE",
};

export const PRODUCT_ACTIONS = {
  GET_PRODUCTS_REQUEST: "PRODUCT_GET_PRODUCTS_REQUEST",
  GET_PRODUCTS_SUCCESS: "PRODUCT_GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_FAILURE: "PRODUCT_GET_PRODUCTS_FAILURE",

  //Save product
  SAVE_PRODUCT_REQUEST: "PRODUCT_SAVE_PRODUCT_REQUEST",
  SAVE_PRODUCT_SUCCESS: "PRODUCT_SAVE_PRODUCT_SUCCESS",
  SAVE_PRODUCT_FAILURE: "PRODUCT_SAVE_PRODUCT_FAILURE",

  //Update product
  UPDATE_PRODUCT_REQUEST: "PRODUCT_UPDATE_PRODUCT_REQUEST",
  UPDATE_PRODUCT_SUCCESS: "PRODUCT_UPDATE_PRODUCT_SUCCESS",
  UPDATE_PRODUCT_FAILURE: "PRODUCT_UPDATE_PRODUCT_FAILURE",

  //Delete product
  DELETE_PRODUCT_REQUEST: "PRODUCT_DELETE_PRODUCT_REQUEST",
  DELETE_PRODUCT_SUCCESS: "PRODUCT_DELETE_PRODUCT_SUCCESS",
  DELETE_PRODUCT_FAILURE: "PRODUCT_DELETE_PRODUCT_FAILURE",
};

export const RESTAURANT_ACTIONS = {
  GET_RESTAURANTS_REQUEST: "RESTAURANT_GET_RESTAURANTS_REQUEST",
  GET_RESTAURANTS_SUCCESS: "RESTAURANT_GET_RESTAURANTS_SUCCESS",
  GET_RESTAURANTS_FAILURE: "RESTAURANT_GET_RESTAURANTS_FAILURE",

  //Update restaurant
  UPDATE_RESTAURANT_REQUEST: "RESTAURANT_UPDATE_RESTAURANT_REQUEST",
  UPDATE_RESTAURANT_SUCCESS: "RESTAURANT_UPDATE_RESTAURANT_SUCCESS",
  UPDATE_RESTAURANT_FAILURE: "RESTAURANT_UPDATE_RESTAURANT_FAILURE",
};
