export const AUTH_ACTIONS = {
  LOGIN_REQUEST: "AUTH_LOGIN_REQUEST",
  LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  LOGIN_FAILURE: "AUTH_LOGIN_FAILURE",
};

export const PRODUCT_ACTIONS = {
  GET_PRODUCTS_REQUEST: "PRODUCT_GET_PRODUCTS_REQUEST",
  GET_PRODUCTS_SUCCESS: "PRODUCT_GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_FAILURE: "PRODUCT_GET_PRODUCTS_FAILURE",
};
