export const AUTH_ACTIONS = {
  LOGIN_REQUEST: "AUTH_LOGIN_REQUEST",
  LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  LOGIN_FAILURE: "AUTH_LOGIN_FAILURE",
};

export const PRODUCT_ACTIONS = {
  GET_PRODUCTS_REQUEST: "PRODUCT_GET_PRODUCTS_REQUEST",
  GET_PRODUCTS_SUCCESS: "PRODUCT_GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_FAILURE: "PRODUCT_GET_PRODUCTS_FAILURE",

  //Save product
  SAVE_PRODUCT_REQUEST: "PRODUCT_SAVE_PRODUCT_REQUEST",
  SAVE_PRODUCT_SUCCESS: "PRODUCT_SAVE_PRODUCT_SUCCESS",
  SAVE_PRODUCT_FAILURE: "PRODUCT_SAVE_PRODUCT_FAILURE",

  //Update product
  UPDATE_PRODUCT_REQUEST: "PRODUCT_UPDATE_PRODUCT_REQUEST",
  UPDATE_PRODUCT_SUCCESS: "PRODUCT_UPDATE_PRODUCT_SUCCESS",
  UPDATE_PRODUCT_FAILURE: "PRODUCT_UPDATE_PRODUCT_FAILURE",

  //Toggle product
  TOGGLE_PRODUCT_REQUEST: "PRODUCT_TOGGLE_PRODUCT_REQUEST",
  TOGGLE_PRODUCT_SUCCESS: "PRODUCT_TOGGLE_PRODUCT_SUCCESS",
  TOGGLE_PRODUCT_FAILURE: "PRODUCT_TOGGLE_PRODUCT_FAILURE",
};

export const RESTAURANT_ACTIONS = {
  GET_RESTAURANTS_REQUEST: "RESTAURANT_GET_RESTAURANTS_REQUEST",
  GET_RESTAURANTS_SUCCESS: "RESTAURANT_GET_RESTAURANTS_SUCCESS",
  GET_RESTAURANTS_FAILURE: "RESTAURANT_GET_RESTAURANTS_FAILURE",

  //Save restaurant
  SAVE_RESTAURANT_REQUEST: "RESTAURANT_SAVE_RESTAURANT_REQUEST",
  SAVE_RESTAURANT_SUCCESS: "RESTAURANT_SAVE_RESTAURANT_SUCCESS",
  SAVE_RESTAURANT_FAILURE: "RESTAURANT_SAVE_RESTAURANT_FAILURE",

  //Update restaurant
  UPDATE_RESTAURANT_REQUEST: "RESTAURANT_UPDATE_RESTAURANT_REQUEST",
  UPDATE_RESTAURANT_SUCCESS: "RESTAURANT_UPDATE_RESTAURANT_SUCCESS",
  UPDATE_RESTAURANT_FAILURE: "RESTAURANT_UPDATE_RESTAURANT_FAILURE",

  //Toggle restaurant
  TOGGLE_RESTAURANT_REQUEST: "RESTAURANT_TOGGLE_RESTAURANT_REQUEST",
  TOGGLE_RESTAURANT_SUCCESS: "RESTAURANT_TOGGLE_RESTAURANT_SUCCESS",
  TOGGLE_RESTAURANT_FAILURE: "RESTAURANT_TOGGLE_RESTAURANT_FAILURE",
};

export const CATEGORY_ACTIONS = {
  GET_CATEGORIES_REQUEST: "CATEGORY_GET_CATEGORIES_REQUEST",
  GET_CATEGORIES_SUCCESS: "CATEGORY_GET_CATEGORIES_SUCCESS",
  GET_CATEGORIES_FAILURE: "CATEGORY_GET_CATEGORIES_FAILURE",
};
